GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/1

###

GET http://localhost:3001/info

###

DELETE http://localhost:3001/api/persons/1

###

POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name": "Donald Duck",
    "number": "040-123-4567"
}

###

POST http://localhost:3001/api/persons
Content-type: application/json

{
    "name": "Mary Poppendieck",
    "number": "040-123-4567"
}

###

POST http://localhost:3001/api/persons 
Content-type: application/json

{
    "number": "040-123-4567"
}

# Some example requests for the Render application below

###

GET https://fullstackopen-phonebook-5m3l.onrender.com/api/persons/

###

GET https://fullstackopen-phonebook-5m3l.onrender.com/api/persons/1

###

GET https://fullstackopen-phonebook-5m3l.onrender.com/info

###

POST https://fullstackopen-phonebook-5m3l.onrender.com/api/persons/
Content-type: application/json

{
    "name": "Donald Duck",
    "number": "040-123-4567"
}

###
