POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "someAuthor", "name": "ST Author", "password": "auth1"
}

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Something", "author": "Another Author", "url": "author.com", "likes": 5
}

###

POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
  "title": "Ducking around", "author": "Donald Duck", "url": "String", "likes": 5
}

###

POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
  "title": "New Task", "author": "MOOC", "url": "url/mooc", "likes": 100
}

###

PUT http://localhost:3003/api/blogs/6853e580a3ef8d1f00f56b6b
Content-Type: application/json

{
  "title": "Still Ducking", "author": "Donald Duck", "url": "String", "likes": 10
}

###

GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/1234

###

DELETE http://localhost:3003/api/blogs/6853e892f57f4721a57e90af

###

POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
  "title": "New", "author": "New", "url": "url/new", "likes": 100
}